EXP:
  # this will be used for logging and model saving
  NAME: "ClosedWorldNoDef-lstm"

MODEL:
  NAME: "lstm"
  # test model?
  TEST: False
  CLASSES: 95
  DEVICE: "cuda"
  # use multiple gpus?
  PARALLEL: True

DATASET:
  TRAIN: "ClosedWorldNoDef.train"
  VAL: "ClosedWorldNoDef.val"
  TEST: "ClosedWorldNoDef.test"

TRAIN:
  RESUME: True
  MAX_EPOCHS: 30
  BATCH_SIZE: 128
  # checkpoint every ? iterations
  CHECKPOINT_PERIOD: 500

TENSORBOARD:
  IS_ON: True
  TARGETS:
    SCALAR: ["loss", "accuracy"]

VAL:
  IS_ON: True
  BATCH_SIZE: 128

TEST:
  BATCH_SIZE: 128

