EXP:
  # this will be used for logging and model saving
  NAME: "ClosedWorldWTFPAD"

MODEL:
  NAME: "dfnet"
  # test model?
  TEST: False
  CLASSES: 96
  DEVICE: "cuda"
  # use multiple gpus?
  PARALLEL: True

DATASET:
  TRAIN: "ClosedWorldWTFPAD.train"
  VAL: "ClosedWorldWTFPAD.val"
  TEST: "ClosedWorldWTFPAD.test"

TRAIN:
  RESUME: True
  MAX_EPOCHS: 30
  BATCH_SIZE: 64
  # checkpoint every ? iterations
  CHECKPOINT_PERIOD: 2500

VAL:
  IS_ON: True
  BATCH_SIZE: 1

TEST:
  BATCH_SIZE: 1

MODEL_DIR: "data/model"
