EXP:
  # this will be used for logging and model saving
  NAME: "ClosedWorldWTFPAD"

MODEL:
  NAME: "dfnet"
  # test model?
  TEST: False
  CLASSES: 95
  DEVICE: "cuda"
  # use multiple gpus?
  PARALLEL: True

DATASET:
  TRAIN: "ClosedWorldWTFPAD.train"
  VAL: "ClosedWorldWTFPAD.val"
  TEST: "ClosedWorldWTFPAD.test"

TRAIN:
  RESUME: True
  MAX_EPOCHS: 30
  BATCH_SIZE: 128
  # checkpoint every ? iterations
  CHECKPOINT_PERIOD: 500

TENSORBOARD:
  IS_ON: True
  TARGETS:
    SCALAR: ["loss", "accuracy"]

VAL:
  IS_ON: True
  BATCH_SIZE: 128

TEST:
  BATCH_SIZE: 128

