EXP:
  # this will be used for logging and model saving
  NAME: "ClosedWorldNoDef"

MODEL:
  NAME: "dfnet"
  # test model?
  TEST: False
  CLASSES: 96
  DEVICE: "cuda"
  # use multiple gpus?
  PARALLEL: True

DATASET:
  TRAIN: "ClosedWorldNoDef.train"
  VAL: "ClosedWorldNoDef.val"
  TEST: "ClosedWorldNoDef.test"

TRAIN:
  RESUME: True
  MAX_EPOCHS: 30
  BATCH_SIZE: 64
  # checkpoint every ? iterations
  CHECKPOINT_PERIOD: 2500

VAL:
  IS_ON: True
  BATCH_SIZE: 1

TEST:
  BATCH_SIZE: 1

MODEL_DIR: "data/model"
